env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: "Iu8YTpzVbRWjPfYJdV95FyHREmdIDjvhhEOh0Pr47UMNYqQfM9+Ag+jibe/cmOHV99zqYbxiGX+pfEUCaVMaza4urXdh4XedOO8NPefa5MP8LLqk9px3UmplaAZ02o015UTu+8OliRAQ8uy9qQhufIx09oHqznTGN4868SAAdI4="
    - secure: "nxGfq7fI7V4FA8CzuPilfaO59xdeyqmxDnjAzwpMtiidxg/zucKf03EahdnCAzr8f4llixBDacttL4dX5Oz0JgfSH5ekFAivUctmpGmy+o1KKPzeTzx9WlwNGx3ycA8Sa1vOzUAOOP0WanFoWC/aEEbzk+M1F+dOrtlwJgLdCcA="

language: ruby
rvm:
  - 2.2.0

install: bundle install --jobs=3 --retry=3
script: bash cibuild.sh
#after_script: if [ "$TRAVIS_BRANCH" == "gh-pages" ]; then travis_retry bundle exec s3_website push; fi

cache: bundler

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test AND deploy the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-", but do NOT deploy it

sudo: false # route the build to the container-based infrastructure for a faster build
